#
# Gitlab-runner config to run this CI script
#

# /etc/gitlab-runner/config.toml
#
# generate by running: 
# sudo gitlab-runner register
#
# Just make sure that afterwards there is following settings added: 
# pull_policy = "if-not-present"
# volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
# privileged = true
# 

concurrent = 4
check_interval = 0

[session_server]
  session_timeout = 1800

  [[runners]]
    name = "docker-with-host-socket-shared"
    url = "<gitlab url>"
    token = "<access token>"
    executor = "docker"
    environment = ["DOCKER_HOST=unix:///var/run/docker.sock"]
    [runners.custom_build_dir]
    [runners.docker]
      tls_verify = false
      image = "docker:stable"
      privileged = true
      disable_entrypoint_overwrite = false
      oom_kill_disable = false
      disable_cache = false
      volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
      pull_policy = "if-not-present"
      [runners.cache]
      [runners.cache.s3]
      [runners.cache.gcs]

